CREATE TABLE USERINFO 
	  (
	USERNUM NUMBER(3,0), 
	ID VARCHAR2(20) NOT NULL, 
	PWD VARCHAR2(20) NOT NULL, 
	NAME VARCHAR2(10) NOT NULL, 
	NICKNAME VARCHAR2(10) NOT NULL, 
	ADDR VARCHAR2(50), 
	EMAIL VARCHAR2(20), 
	BIRTH VARCHAR2(10), 
	PHONE VARCHAR2(20), 
	ISLIVE NUMBER NOT NULL
   	);


  ALTER TABLE USERINFO ADD CONSTRAINT USERINFO_PK PRIMARY KEY (USERNUM);
  
--------------------------------------------------------------------------------------------
CREATE TABLE MESSAGE 
	  (
	MESS_NUM NUMBER, 
	REC_USERNUM NUMBER NOT NULL, 
	SEND_USERNUM NUMBER NOT NULL, 
	MESS_TITLE VARCHAR2(30) NOT NULL, 
	MESS_CONTENT VARCHAR2(100) NOT NULL, 
	SEND_TIME DATE NOT NULL, 
	CHECK_READ VARCHAR2(20)
   	);

  ALTER TABLE MESSAGE ADD CONSTRAINT MESSAGE_PK PRIMARY KEY (MESS_NUM);
  
 ALTER TABLE MESSAGE ADD CONSTRAINT MESSAGE_FK1 FOREIGN KEY (REC_USERNUM) REFERENCES USERINFO (USERNUM);
 ALTER TABLE MESSAGE ADD CONSTRAINT MESSAGE_FK2 FOREIGN KEY (SEND_USERNUM) REFERENCES USERINFO (USERNUM);
--------------------------------------------------------------------------------------------
CREATE TABLE CATTABLE 
	 (
	CATNUM_PK NUMBER, 
	CATNAME VARCHAR2(20) NOT NULL
   	);

  ALTER TABLE CATTABLE ADD CONSTRAINT "CATTABLE_PK" PRIMARY KEY ("CATNUM_PK");
--------------------------------------------------------------------------------------------
CREATE TABLE CAFEGRADE 
   	(	
	GRADE_NUM NUMBER, 
	GRADE_NAME VARCHAR2(20) NOT NULL
  	);

ALTER TABLE CAFEGRADE ADD CONSTRAINT CAFEGRADE_PK PRIMARY KEY (GRADE_NUM);
--------------------------------------------------------------------------------------------
CREATE TABLE CAFELIST
	(	
	CAFENUM NUMBER, 
	GRADE_NUM NUMBER NOT NULL, 
	CATNUM NUMBER NOT NULL, 
	CAFENAME VARCHAR2(20) NOT NULL , 
	USERNUM NUMBER NOT NULL
   	);

ALTER TABLE CAFELIST ADD CONSTRAINT CAFELIST_PK PRIMARY KEY (CAFENUM);
ALTER TABLE CAFELIST ADD CONSTRAINT CAFELIST_FK2 FOREIGN KEY (CATNUM) REFERENCES CATTABLE(CATNUM_PK);
ALTER TABLE CAFELIST ADD CONSTRAINT CAFELIST_FK1 FOREIGN KEY (GRADE_NUM) REFERENCES CAFEGRADE(GRADE_NUM);
ALTER TABLE CAFELIST ADD CONSTRAINT CAFELIST_FK3 FOREIGN KEY (USERNUM) REFERENCES USERINFO(USERNUM);
--------------------------------------------------------------------------------------------
 CREATE TABLE CAFEMEMGRADE 
   	(	
	CAFENUM NUMBER, 
	CAFEMEM_GRADE NUMBER NOT NULL, 
	CAFEMEM_GRADE_NAME VARCHAR2(20)
   	);

  ALTER TABLE CAFEMEMGRADE ADD CONSTRAINT CAFEMEMGRADE_PK PRIMARY KEY (CAFEMEM_GRADE);

  ALTER TABLE CAFEMEMGRADE ADD CONSTRAINT CAFEMEMGRADE_FK1 FOREIGN KEY (CAFENUM) REFERENCES CAFELIST (CAFENUM);
--------------------------------------------------------------------------------------------
CREATE TABLE CAFEMEMBER 
	(
	USERNUM NUMBER, 
	CAFENUM NUMBER NOT NULL, 
	CAFEMEMNICK VARCHAR2(20), 
	CAFEMEMGRADE NUMBER
   	);

  ALTER TABLE CAFEMEMBER ADD CONSTRAINT CAFEMEMBER_PK1 PRIMARY KEY (USERNUM);

 ALTER TABLE CAFEMEMBER ADD CONSTRAINT CAFEMEMBER_FK1 FOREIGN KEY (USERNUM) REFERENCES USERINFO (USERNUM);
 ALTER TABLE CAFEMEMBER ADD CONSTRAINT CAFEMEMBER_FK2 FOREIGN KEY (CAFENUM) REFERENCES CAFELIST (CAFENUM);
  ALTER TABLE CAFEMEMBER ADD CONSTRAINT CAFEMEMBER_FK3 FOREIGN KEY (CAFEMEMGRADE) REFERENCES CAFEMEMGRADE (CAFEMEM_GRADE);
--------------------------------------------------------------------------------------------
CREATE TABLE CAFEBOARDCAT 
	(
	BOARDCATNUM NUMBER, 
	CAFENUM_FK NUMBER not null, 
	CATNAME VARCHAR2(30) not null, 
	CATORDER NUMBER not null
   	);

ALTER TABLE CAFEBOARDCAT ADD CONSTRAINT CAFEBOARDCAR_PK PRIMARY KEY (BOARDCATNUM);

ALTER TABLE CAFEBOARDCAT ADD CONSTRAINT CAFEBOARDCAT_FK1 FOREIGN KEY (CAFENUM_FK) REFERENCES CAFELIST (CAFENUM);
--------------------------------------------------------------------------------------------
CREATE TABLE CAFEBOARD 
	(
	BOARDNUM NUMBER, 
	CAFENUM NUMBER not null, 
	BOARD_CAT_NUM NUMBER not null, 
	BOARD_NAME VARCHAR2(30) not null, 
	ORDERNUM NUMBER not null
	
	);

	ALTER TABLE CAFEBOARD ADD CONSTRAINT BOARDNUM_PK PRIMARY KEY (BOARDNUM); 

	ALTER TABLE CAFEBOARD ADD CONSTRAINT CAFEBOARD_FK1 FOREIGN KEY (CAFENUM) REFERENCES CAFELIST (CAFENUM);
  	ALTER TABLE CAFEBOARD ADD CONSTRAINT CAFEBOARD_FK2 FOREIGN KEY (BOARD_CAT_NUM) REFERENCES CAFEBOARDCAT (BOARDCATNUM);
--------------------------------------------------------------------------------------------
 CREATE TABLE POSTCATTABLE 
   	(	
	POST_CAT_NUM NUMBER, 
	CAFE_NUM NUMBER NOT NULL, 
	POST_CAT_NAME VARCHAR2(15) NOT NULL
   	);

  ALTER TABLE POSTCATTABLE ADD CONSTRAINT POSTCATTABLE_PK PRIMARY KEY (POST_CAT_NUM);
--------------------------------------------------------------------------------------------
  CREATE TABLE POST 
   	(	
	POSTNUM NUMBER, 
	BOARDNUM NUMBER, 
	CAFENUM NUMBER, 
	POST_TITLE VARCHAR2(30), 
	POST_CONTENT VARCHAR2(100), 
	POST_DATE DATE, 
	USER_NUM VARCHAR2(20), 
	PST_CAT_NUM NUMBER NOT NULL
   	);

  ALTER TABLE POST ADD CONSTRAINT POST_PK PRIMARY KEY (POSTNUM);

	ALTER TABLE POST ADD CONSTRAINT POST_FK1 FOREIGN KEY (BOARDNUM) REFERENCES CAFEBOARD (BOARDNUM);
  	ALTER TABLE POST ADD CONSTRAINT POST_FK2 FOREIGN KEY (CAFENUM) REFERENCES CAFELIST (CAFENUM);
  	ALTER TABLE POST ADD CONSTRAINT POST_FK3 FOREIGN KEY (POSTNUM) REFERENCES USERINFO (USERNUM);
  	ALTER TABLE POST ADD CONSTRAINT POST_FK4 FOREIGN KEY (PST_CAT_NUM) REFERENCES POSTCATTABLE (POST_CAT_NUM);

--------------------------------------------------------------------------------------------
 CREATE TABLE FILETABLE 
   	(	
	FINENUM NUMBER, 
	POSTNUM NUMBER NOT NULL, 
	SAVEFILENAME VARCHAR2(40) NOT NULL, 
	ORGFILENAME VARCHAR2(30) NOT NULL
   	);

  	ALTER TABLE FILETABLE ADD CONSTRAINT FILENUM_PK PRIMARY KEY (FINENUM);

	ALTER TABLE FILETABLE ADD CONSTRAINT POSTNUM_FK FOREIGN KEY (POSTNUM) REFERENCES POST (POSTNUM);
--------------------------------------------------------------------------------------------
  CREATE TABLE IMGTABLE 
	 (	
	 IMGNUM NUMBER, 
	 POSTNUM NUMBER NOT NULL, 
	 SAVEIMGNAME VARCHAR2(30) NOT NULL, 
	 ORGIMGNAME VARCHAR2(30) NOT NULL
   	);

  ALTER TABLE IMGTABLE ADD CONSTRAINT IMGNUM_PK PRIMARY KEY (IMGNUM);

  ALTER TABLE IMGTABLE ADD CONSTRAINT IMGTABLE_FK FOREIGN KEY (POSTNUM) REFERENCES POST (POSTNUM);
--------------------------------------------------------------------------------------------